import type { FixedBill, Installment } from "./types";

export const MOCK_BILLS: FixedBill[] = [
  {
    id: "1",
    name: "Adobe Creative Cloud",
    category: "Software",
    amount: 54.99,
    recurrence: "monthly",
    dueDay: 5,
    status: "paid",
  },
  {
    id: "2",
    name: "Office Rent",
    category: "Moradia",
    amount: 1200,
    recurrence: "monthly",
    dueDay: 10,
    status: "pending",
  },
  {
    id: "3",
    name: "AWS Cloud Hosting",
    category: "Infraestrutura",
    amount: 89,
    recurrence: "monthly",
    dueDay: 15,
    status: "overdue",
  },
  {
    id: "4",
    name: "Netflix",
    category: "Lazer",
    amount: 45,
    recurrence: "monthly",
    dueDay: 20,
    status: "paid",
  },
  {
    id: "5",
    name: "Spotify",
    category: "Lazer",
    amount: 21.9,
    recurrence: "monthly",
    dueDay: 22,
    status: "pending",
  },
  {
    id: "6",
    name: "iCloud 2TB",
    category: "Software",
    amount: 12.9,
    recurrence: "monthly",
    dueDay: 8,
    status: "paid",
  },
];

export const MOCK_INSTALLMENTS: Installment[] = [
  {
    id: "1",
    name: "MacBook Pro",
    category: "Tecnologia",
    totalAmount: 12000,
    paidAmount: 4000,
    totalInstallments: 12,
    paidInstallments: 4,
    dueDay: 10,
    startDate: "2026-01-10",
  },
  {
    id: "2",
    name: "iPhone 15",
    category: "Tecnologia",
    totalAmount: 6000,
    paidAmount: 3000,
    totalInstallments: 12,
    paidInstallments: 6,
    dueDay: 15,
    startDate: "2025-11-15",
  },
  {
    id: "3",
    name: "Curso React Native",
    category: "Educação",
    totalAmount: 1800,
    paidAmount: 1200,
    totalInstallments: 6,
    paidInstallments: 4,
    dueDay: 5,
    startDate: "2026-01-05",
  },
  {
    id: "4",
    name: "Geladeira Samsung",
    category: "Eletrodoméstico",
    totalAmount: 3600,
    paidAmount: 600,
    totalInstallments: 12,
    paidInstallments: 2,
    dueDay: 18,
    startDate: "2026-03-18",
  },
];
