import type { Transaction } from "./types";

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "1",
    description: "Freelance React",
    category: "Desenvolvimento",
    date: "2026-05-01",
    type: "entrada",
    amount: 4500,
    status: "recebido",
  },
  {
    id: "2",
    description: "Uber Ride",
    category: "Transporte",
    date: "2026-05-02",
    type: "gasto",
    amount: 24.5,
    status: "pago",
  },
  {
    id: "3",
    description: "Salário",
    category: "Trabalho",
    date: "2026-05-05",
    type: "entrada",
    amount: 8000,
    status: "recebido",
  },
  {
    id: "4",
    description: "Supermercado",
    category: "Alimentação",
    date: "2026-05-06",
    type: "gasto",
    amount: 320,
    status: "pago",
  },
  {
    id: "5",
    description: "Consultoria UX",
    category: "Desenvolvimento",
    date: "2026-05-08",
    type: "entrada",
    amount: 2100,
    status: "pendente",
  },
  {
    id: "6",
    description: "Netflix",
    category: "Lazer",
    date: "2026-05-10",
    type: "gasto",
    amount: 45,
    status: "pago",
  },
  {
    id: "7",
    description: "Freelance Node",
    category: "Desenvolvimento",
    date: "2026-05-12",
    type: "entrada",
    amount: 3200,
    status: "recebido",
  },
  {
    id: "8",
    description: "Academia",
    category: "Saúde",
    date: "2026-05-14",
    type: "gasto",
    amount: 120,
    status: "pago",
  },
  {
    id: "9",
    description: "Aluguel",
    category: "Moradia",
    date: "2026-05-15",
    type: "gasto",
    amount: 1800,
    status: "pago",
  },
  {
    id: "10",
    description: "Dividendos",
    category: "Investimentos",
    date: "2026-05-18",
    type: "entrada",
    amount: 650,
    status: "recebido",
  },
];
